language: generic
sudo: required
services:
  - docker

deploy:
  provider: packagecloud
  repository: "ci"
  username: "ergw"
  token:
    secure: "CcYGWsBd27IKoBsFxXO3U4AGGNtpKDzlDim2y0O9N3ddAOcpgfFN2oQ1Wh/QgvqKa+BYgom5np4mGp6aTPPeo4gcmSxvsbPPiRhEkom5SOfJP/03MuvBsvRd8VXwEBpV9C2vnnYJTx5flgk7md7f+ZViordNLrClXPEqPB01dzht0Q/TPSA3Q6OWsxOUXA0VtbpKx2iwtViCCeXj4uuR4p6d64r698rdcENHQ7GWqwNlWwNm5pdH+6MEakm76sRyfcDGEbaujzfyXOsGj2s8XgOe7aY3BZXqq+8CEQg/iUiO4zu/e8HVLIPLxXwsbea9JyH68D0fNEHOiONCWkVzYAlU6NBHikSI3syboKgAfL6znHT6EeJqVPpFyb9gRRukbGxQBztTu/4FEpa3MPNdC9hDeeHfqOdDWK8INCGtCdHTGE6gvKd4gE5etPWm2NNYTpnOw1FFAIbPL+38xW/WrG7dNYmvsVFIWl1rhoQWb24kkL1sBMXTaSKdBbI0pEC6nUYtI2BtlzEqi/oRpBrZ6ThRGzjTli4rcKB8a28YvC5Y3sK+6ORADy6gYYWjgTTwT5nquP+Yqn9QUZg5puHdTiUEvCxYNFhsZwWBzcngvMUwTMehsuz6yM7SL6UAdoaK7zDF5v2KCZZ5HNkrFN98Rfn7/gCfHjPGxlqOgtluAx0="
  dist: "ubuntu/xenial"
  skip_cleanup: true
  package_glob: artifacts/*.deb

env:
  global:
    - BUILD_IMAGE="ergw/ergw-gtp-c-node"
    - DOCKER_USERNAME="ergwci"
    - secure: "dWQgAWw3Z9Yw4L/W9v8nRG1a6LgGzkko8E8PDEFhaHeVl41woB7+bzuydpSs9whdjkwyIzUspCrt5G8s1qUW9w/anoyWYgKZ3PRfEJM5x6+kO/zcJR5n2hzwcKXcPVJSitc864gQJOdO87Rm6sLGtL/fQT/fo15SxZUsQgwF5kRASe0+iKpCo7/lvqjw8q95Qpeadc9+3hM7yPr9rVWLkHK9rczL9QjPqwVOHJdlQEjrdMpopzNmPLTegiFodaxL5m85stCS8Sqd/CxgVw2B8Uz0VqRO4vWR9Rh6tsggtRQEqCNHI+NgzUW1jBCEoAYNZQVMdbBBLrUwd8Hj38Z6SKRtjpd2VNaXxERj2nIiqQHDoSIM4ObQcYqt5P4StFa8e5u5Ukl7e3IACstjKWDvgZly1SwdCV5YK0HIYMMX/lnHnO1no92/dMB9eOM+PnDI/DsQhF6nuCYGF1hyBHutuAlDoPJE5MX82g30ZCSYpsspoHxIukE8oboUx0yMhcFFDcJ3WqbDWlZvXYr7abmhIrqQmStQoWHUk4svTuH8y4+ZLb2cywHZ1wZOhBUqPyvh2AjH1YeFMIl72fuUvOjz5CKYjzCzQ3geEpyyMCU10kGIPMNf4sTMlk4ILIabFixniTk8ZFLwAcoduR8PK6psWdcaHtEw+GwjuITcHW6szVo="

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y devscripts
  - docker build -t ergw -f priv/Dockerfile priv

script:
  - export SHORT_COMMIT_ID=$(git rev-parse --verify --short $TRAVIS_COMMIT)
  - debchange -m -l "+$TRAVIS_JOB_NUMBER+git$SHORT_COMMIT_ID" 'Automatically built'
  - mkdir artifacts
  - docker run -v `pwd`:/build ergw
    sh -c "
      dpkg-buildpackage -b -uc -nc && cp ../*deb artifacts
    "
  - docker build -t $BUILD_IMAGE -f docker/Dockerfile . 

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - export TAG=`if [ "$TRAVIS_EVENT_TYPE" == "pull_request" ]; then echo PR-$TRAVIS_PULL_REQUEST_BRANCH ; else echo $TRAVIS_BRANCH ; fi`
  - if [ "$TAG" == "master" ]; then export TAG="latest"; fi
  - docker tag $BUILD_IMAGE $BUILD_IMAGE:$TAG
  - docker push $BUILD_IMAGE:$TAG
  - echo "docker push done"


notifications:
  slack:
    - secure: "cXUINZF8EN0aE896uS+bB+beV4qmnhVRY1T3CXpkxWUQ/tPkvX5tWsyp87XEOUJBACxNAqn6LJoOVVP7/86CS8Ry8eBt5WJTdx3y+frUyKEz6iv2cX2ULhQ61u8YMGydTo+rMkoxyxMbHN5LM+PjmTOzDnByrjPP2u70t+93x9AZrxbgmNREHCvLV9kQEXLQbRTTbEQxOOP0+acNvanNNfpqSaprTfMmsGoetHNKmSiaMuf5iixvV47FHDfrOGeZ5jk+JgnRiHsRH7oq1rLu16gUmM3Jvj84TgdfTFiLrXFOqW26g6/fvuNwlzP2tvLTOPTJElE0/3xYVSxFoNhfA2+V77S11PwQR0rdrEmT64kNI6UKk9CuEeNdIkx0uCWz/5+ahvEaPB/nqB5/wJYZsDbipmng6zXzS7FXkY3hBbUdyoMAUtEYKPx6zg/VJZ4yUgmpvoTgY9IeR0/1Sv1RsyVu/SPWS+x7uO4TyMcVIDx07PNuW4gqfu9k7j57lMtfeu7FBjHlN8KfckLSehCN/+yKtzER5rIH1pKrdVRJLpWy4ny0Hpx4kZZKTIknZF0GRZTpcyyiNUqf+8vgpGZPQsxvT6xut7PGMockSKM8SPEhXalTBmbJRtkm7CdDxD2AgfSEuORWZE1eFMQjn2iah2uOTUd3YOddiRL6ptRL85s="

branches:
  only:
    - master
